FUSETOOLS2-1731: Migrating to @vscode/test-electron package
camel-tooling/vscode-camelk pull request #1245
Opened 2022-08-29 08:29 UTC by joshiraez

WIP: Wanting to test the migration on github ci.

Related issue: https://issues.redhat.com/browse/FUSETOOLS2-1731

2022-08-30 15:40 UTC, joshiraez commented
Commenting that even though Mikhail's PR addresed the migration, it was to a much lower version. So I think it is good to follow up with this one too.

https://github.com/camel-tooling/vscode-camelk/pull/1224/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R378

2022-08-31 08:50 UTC, apupier requested changes
i think that it would be better to clean the commit history as it contains 4 commits with no information on the real change. (Submitting to test on CI, Uploading to test in CI, fix merge conflict, rebase with upstream)

2022-08-31 09:22 UTC, joshiraez commented
It's squashed up now. I went ahead and squashed up the similar PR in VSCode AtlasMap

2022-08-31 09:39 UTC, apupier approved these changes

2022-08-31 10:18 UTC, merged