Fusetools2 572 clean code before starting
camel-tooling/vscode-camelk pull request #546
Opened 2020-09-16 13:44 UTC by apupier

2020-09-17 12:54 UTC, bfitzpat requested changes

2020-09-17 12:54 UTC, bfitzpat commented on src/test/suite/z_extension.test.ts
> +	test('test namespace provided to getBaseCmd contain --namespace parameter', function() {
contains instead of contain here

2020-09-17 12:54 UTC, bfitzpat commented on src/test/suite/z_extension.test.ts
> +		assert.equal(namespaceConfigValueAfterReset, testNs, 'The setted value should be available.');
"setted" is not really a word -- perhaps change to "The value set should be available"

2020-09-17 13:24 UTC, apupier commented on src/test/suite/z_extension.test.ts
> +	test('test no namespace provided to getBaseCmd doesn\'t contain --namespace parameter', function() {
isn't "missing" to be used when something should be here but it isn't?
the --namespace is not really missing. it is not provided on purpose.

2020-09-17 16:02 UTC, bfitzpat commented on src/test/suite/z_extension.test.ts
> +	test('test no namespace provided to getBaseCmd doesn\'t contain --namespace parameter', function() {
then I would say 'test that getBaseCmd doesn't contain --namespace parameter when no namespace is passed' - that's much more clear

2020-09-18 13:24 UTC, bfitzpat approved these changes

2020-09-18 13:52 UTC, merged