FUSETOOLS2-1094 - provide more precise error message in test failure for
camel-tooling/vscode-camelk pull request #745
Opened 2021-04-29 13:41 UTC by apupier

expected completion not found

the error will be something like:

```
  7) Should do completion in yaml Camel K files without file name pattern
       Completes for first level:
     Error: Error: Timed out after waiting for 10000 ms
Cannot found expected completion "test" in the list of completions:
error-handler
from
my-added-property-for-the-demo
on-exception
rest
route
```

instead of somethign like:
```
  1) Should do completion in Camel K standalone files
       Completes additional dependencies:
     Error: Timed out after waiting for 10000 ms
  	at /home/circleci/project/node_modules/async-wait-until/dist/index.js:1:1034
 ```

2021-04-29 14:11 UTC, apupier commented
might help to understand why it is failing mostly all the time on this other PR https://github.com/camel-tooling/vscode-camelk/pull/743 (and often on others but not reproduced on this one)

2021-04-29 14:11 UTC, lhein approved these changes

2021-04-30 14:13 UTC, bfitzpat requested changes
Language should change slightly. "found" vs "find"

2021-04-30 14:13 UTC, bfitzpat commented on src/test/suite/completion.util.ts
> +		throw new Error(`${err}\nCannot found expected completion "${expectedCompletion.label}" in the list of completions:\n${errorMessage}`);
Can we change `Cannot found` to `Cannot find`?

2021-04-30 14:27 UTC, bfitzpat approved these changes

2021-04-30 15:03 UTC, merged